### ISSUE TITLE
Hutchinson Index of Duration (counts) and Severity (sums)

### ISSUE THREAD

**Issue by ivanhanigan** [royalosyin/Calculate-Precipitation-based-Agricultural-Drought-Indices-with-Python#1]
Hi @royalosyin 

this is a great site.

I am the co-author of the Hutchinson R package you refer to.
I just want to ask if you also look at the duration and severity indicators (based on counting consecutive months where the rescaled percentiles are continuously below a threshold, or using sums of the rescaled values to add up consecutive scores that are continuously under a threshold) as was the original definition in the 1992 report by Mike Hutchinson?  I cannot see where you have documented that on this site sorry.
https://github.com/ivanhanigan/HutchinsonDroughtIndex/blob/master/inst/doc/HutchinsonDroughtIndex-original.pdf

See duration count method here https://github.com/ivanhanigan/HutchinsonDroughtIndex/blame/master/R/drought_index_stations.r#L84
and see severity sum method here https://github.com/ivanhanigan/HutchinsonDroughtIndex/blame/master/R/drought_index_stations.r#L111

also you say:
"However, it is difficult to apply it for assessing droughts in the future. Although the historical thresholds could be used to identify drought events, it is hard to define their extents of Severity. "
https://github.com/royalosyin/Calculate-Precipitation-based-Agricultural-Drought-Indices-with-Python/blame/master/ex2-Calculate%20Hutchinson%20Drought%20Index%20(HDI).ipynb#L240

I recently published an approach to doing just this that I worked on with Mike Hutchinson.  It uses a 30 year rolling 'look-back' period and this allows for long term drifts in the underlying climate that would lead to adaptation or migration of people, animals and plants.
https://www.mdpi.com/1660-4601/19/13/7855

Cheers,
Ivan.

**Comment by royalosyin** [comment]
Hi, Ivan

Wow. It is posted quite a long ago.
In fact, I also applied it to assess the drought under RCP8.5 in the Australia project under the request of the clients.
Thanks for your comments and your paper link sent to me.
The paper is quite insightful.
Thank a lot.

Best regards
Chonghua

**Comment by ivanhanigan** [comment]
Hi @royalosyin .
I still don't understand if you have applied the duration (count) and severity (sum) steps of the HDSI.  From your code it looks like you just transform the rainfall percentiles onto the scale -4 to +4.  You also have to count consecutive months below -1 (or sum if using severity method).  I am sorry if you made that clear but I have not found it in your codes.

Best regards,
Ivan.
